version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "0.0.0.0:${APP_PORT}:${APP_PORT}"
    command: npm start
    depends_on: 
      - db

  caddy:
    image: caddy:2.4.3
    ports:
      - "${CADDY_80}:${CADDY_80}"
      - "${CADDY_443}:${CADDY_443}"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    
  db:
    image: postgres:latest
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  pgdata: