version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "0.0.0.0:${APP_PORT:-8080}:8080"
    command: npm start
    depends_on: 
      - db

  caddy:
    image: caddy:2.4.3
    ports:
      - "${CADDY_HTTP:-80}:80"
      - "${CADDY_HTTPS:-443}:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    
  db:
    image: postgres:latest
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  pgdata: